typography_spectrum: 0.6848474030848593
color:
  brandColors:
    - '#000000'
    - '#E0E4E3'
    - '#6B717D'
    - '#2B313D'
    - '#F4555E'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-83073550-1
  facebook: null
  twitter: null
author:
  name: Mike Shaw
  email: mike@applimatix.com
name: Lake Narrabeen
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Lake Narrabeen
description: Almost daily pics
purpose: []
