layout_spectrum: 0.24874974437989295
typography_spectrum: 0.979438868816942
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.21210494823753834
  lightness: 0.3813983683940023
  saturation: 0.5819502195809036
  rhythmicContrast: 0.4776710809674114
name: Lake Narrabeen
favicon: null
author:
  name: Mike Shaw
  email: mike@applimatix.com
title: Lake Narrabeen
description: Almost daily pics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-83073550-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
