name: Lake Narrabeen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19262200128287077
author:
  name: Mike Shaw
  email: mike@applimatix.com
title: Lake Narrabeen
description: Almost daily pics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-83073550-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#E0E4E3'
    - '#6B717D'
    - '#2B313D'
    - '#F4555E'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
