layout_spectrum: 0.3773562479764223
typography_spectrum: 0.7376653980463743
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.03500193264335394
  lightness: 0.04385696118697524
  saturation: 0.6929306800011545
  rhythmicContrast: 0.30323349800892174
name: Lake Narrabeen
favicon: null
author:
  name: Mike Shaw
  email: mike@applimatix.com
title: Lake Narrabeen
description: Almost daily imagery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
