layout_spectrum: 0.8450036169961095
typography_spectrum: 0.449751908890903
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.00048300460912287235
  lightness: 0.6523328144103289
  saturation: 0.48282803618349135
  rhythmicContrast: 0.39888963545672596
name: Lake Narrabeen
favicon: null
author:
  name: Mike Shaw
  email: mike@applimatix.com
title: Lake Narrabeen
description: Almost daily pics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-83073550-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
