typography_spectrum: 0.19262200128287077
color:
  brandColors:
    - '#000000'
    - '#E0E4E3'
    - '#6B717D'
    - '#2B313D'
    - '#F4555E'
  brandStrength: 0.256503778276965
  lightness: 0.8606667073909193
  saturation: 0.7115523281972855
  rhythmicContrast: 0.44453981053084135
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8246468924917281
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Mike Shaw
  email: mike@applimatix.com
name: Lake Narrabeen
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Lake Narrabeen
description: Almost daily pics
purpose: []
